name: Link check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.html'
      - '**/*.yml'
      - '**/*.yaml'
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '17 6 * * 1'

permissions:
  contents: read
  issues: write

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --accept 200,204,206,429
            --exclude '.*\{\{.*\}\}.*'
            './**/*.md'
            './**/*.html'
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
